// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZa0oBOIMKXQZc-SsRfYQ8SH16_AKJ_tw',
    appId: '1:261065629680:web:60453bbde50b93b3860735',
    messagingSenderId: '261065629680',
    projectId: 'flutterapp-1d2ca',
    authDomain: 'flutterapp-1d2ca.firebaseapp.com',
    databaseURL: 'https://flutterapp-1d2ca-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-1d2ca.firebasestorage.app',
    measurementId: 'G-C2E5CSC6MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9J3TkbRyFpPXu6ye53ZN489V8RWWkows',
    appId: '1:261065629680:android:d39d81f6c76c93ca860735',
    messagingSenderId: '261065629680',
    projectId: 'flutterapp-1d2ca',
    databaseURL: 'https://flutterapp-1d2ca-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-1d2ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN5ziyq6PRrWKRdZ-I2o90YFhekR61JEA',
    appId: '1:261065629680:ios:51517aa7352418b6860735',
    messagingSenderId: '261065629680',
    projectId: 'flutterapp-1d2ca',
    databaseURL: 'https://flutterapp-1d2ca-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-1d2ca.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN5ziyq6PRrWKRdZ-I2o90YFhekR61JEA',
    appId: '1:261065629680:ios:51517aa7352418b6860735',
    messagingSenderId: '261065629680',
    projectId: 'flutterapp-1d2ca',
    databaseURL: 'https://flutterapp-1d2ca-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-1d2ca.firebasestorage.app',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZa0oBOIMKXQZc-SsRfYQ8SH16_AKJ_tw',
    appId: '1:261065629680:web:f0a2ff8e56ce45bb860735',
    messagingSenderId: '261065629680',
    projectId: 'flutterapp-1d2ca',
    authDomain: 'flutterapp-1d2ca.firebaseapp.com',
    databaseURL: 'https://flutterapp-1d2ca-default-rtdb.firebaseio.com',
    storageBucket: 'flutterapp-1d2ca.firebasestorage.app',
    measurementId: 'G-X2ML6N0M8D',
  );

}